---
- name: Running helloWorld.yml
  hosts: all
  gather_facts: true

  tasks:
    - name: Formating user input (Remove new lines from variable) and setting variables from survey
      file:
        path: ~/ansible_touch.txt
        state: touch
